### PR TITLE
Add utility for comment extraction from structs

### PR DESCRIPTION
**Pull request by rmohr**
@emicklei not sure if you want somethin like that in this repo, but I added a tool which allows extraction of documentation strings from golang structs and provides them in a builder consumable form. It generates maps compatible with the swagger builder in go-restful [1].

If you like it it might also make sense to add it to go-restful.

Looking forward to hear your thoughts.

[1] https://github.com/emicklei/go-restful/blob/7f33558714877d72a21c27e88fe140f264c9e7c9/swagger/README.md

### CODE REVIEW

**Comment by emicklei** [comment]
Hi,

I think having tools to support documentation generation is useful.
However, I hesitate to include tools in this repository given the fact that users will typically vendor swagger2 and there is a potential "danger" to create tools that require other tools for their dependencies.
I would like this package to be an implementation of the spec and a builder for struct->schema only at this moment.
Would you consider adding this to a newly created repo called "swagger2-tools" ?

**Comment by rmohr** [comment]
> Would you consider adding this to a newly created repo called "swagger2-tools" ?

Sure will do a pull request there as soon as the repo is there. Glad you like the tool. Maybe we can find a better name for the tool than `desc` ...

**Comment by rmohr** [comment]
For now it lives in https://github.com/rmohr/go-swagger-utils

**Comment by emicklei** [comment]
@rmohr sorry about the late response. thanks for creating the repo. will work on this next week.

**Pull request closed without merging**
